# Generated by Django 2.2 on 2020-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201029_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Type',
            new_name='transaction_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='United Stated of America', max_length=20, verbose_name='Country'),
        ),
    ]
